### ISSUE TITLE
Implementing triggers

### ISSUE THREAD

**Issue by cuuush** [Team1923/Stronghold_2016#1]
Our current method of assigning buttons to commands is not the best.

`lB.whileHeld(new ElevatorDownCommand());` can be replaced with a trigger

[here's the documentation for trigger](http://first.wpi.edu/FRC/roborio/stable/docs/java/classedu_1_1wpi_1_1first_1_1wpilibj_1_1buttons_1_1Trigger.html)

**Comment by aravindkoneru** [comment]
I don't get it, why is a trigger better? I think the implementation works better with the command-based programming scheme, but what's the advantage?

**Comment by Makarand12676** [comment]
Can you try implementation shown as in link below? This will go well with
command based programming -

https://github.com/owatonnarobotics/XboxController

**Comment by tbruestle** [comment]
It seems to me that Trigger is just the base class that Button inherits from. The descriptions look the same, so I imagine the Button.whileHeld function calls the Trigger.whileActive. Trigger.whileActive is also public, so we can refer to it as Button.whileActive. I can't see how casting the button as its base object would be better.

**Comment by aravindkoneru** [comment]
@Makarand1923 I'm modifying their implementation right now. They use the joysticks on the controller, so there's a lot of extraneous code to remove. I'll make a commit soonish with the updated XboxController class.

**Comment by cuuush** [comment]
Triggers would be useful for button assignments with conditions, such as 70% pressure. This might also be useful for shifting gears, since we don't want to shift down at high speeds.
The downside is it moves logic outside of commands, but it makes an expensive operation (adding a new command) into a cheaper one (checking a boolean)

@tbruestle the intention would be to write our own custom trigger classes, like my examples above.

**Comment by tbruestle** [comment]
If we wanted to use Triggers:
  rB.whileHeld(new ElevatorUpCommand());
becomes
  ((Trigger)rB).whileActive(new ElevatorUpCommand());
or 
  rB.whileActive(new ElevatorUpCommand());
From https://github.com/Team1923/Recycle_Rush_2015/blob/master/src/org/usfirst/frc/team1923/robot/OI.java

The only reason to switch to triggers is if there is something in "whileHeld" that we want to avoid. Theoretically, "whileHeld" should call "whileActive".

**Comment by cuuush** [comment]
We would write our own trigger class, [like this one](https://github.com/Team1923/Recycle_Rush_2015/blob/master/src/org/usfirst/frc/team1923/triggers/RightTrigger.java) (the commented code is what we could do)

From screensteps:

> Additionally commands can be triggered by arbitrary conditions of your choosing by using the Trigger class instead of Button. Triggers (and Buttons) are usually polled every 20ms or whenever the scheduler is called.
