### ISSUE TITLE
We don't need LED subsystem.

### ISSUE THREAD

**Issue by cuuush** [Team1923/Stronghold_2016#3]
Delete the LED subsystem.

**Comment by xavierlyu** [comment]
but LEDs are fun..... and we need those useless programs to prove that we have done stuff :)
Anyway, I will delete it once most people say no

Also, do we need a script that contains all of our robot+match info? such as alliance, match time, station number and so on....

**Comment by Zedai** [comment]
I second the motion.

**Comment by cuuush** [comment]
We'll do this at a later time.

**Comment by Makarand12676** [comment]
Can we try this interesting logging and communication method -
http://www.chiefdelphi.com/forums/showthread.php?t=140729

**Comment by Makarand12676** [comment]
Also read related white paper -
http://www.chiefdelphi.com/media/papers/download/4552
