### ISSUE TITLE
SmartDashboard 2.0 (SFX)

### ISSUE THREAD

**Issue by aravindkoneru** [Team1923/Stronghold_2016#7]
I'm thinking that we should switch over to the new [SmartDashboard](http://wpilib.screenstepslive.com/s/4485/m/26401/l/255406-the-new-smartdashboard-sfx). It looks like it has a lot more functionality and we don't need to add any special code or anything. I think it would be a good idea to get @Team1923/curie-programming and @Team1923/archimedes-programming working on this. It's robot programming and simple enough that most people can participate. Any thoughts?

**Comment by xavierlyu** [comment]
It looks interesting. We should do it after all the robot code is complete, or after Mt. Olive

**Comment by aravindkoneru** [comment]
Nah it's something that we should do in parallel with robot code. We're adding smart dashboard functions anyway so it doesn't make sense to write bad code now and fix it later. If we're going to go down this route, we should decide now. If not, no big deal, we'll just stick with the normal smartdashboard.

**Comment by xavierlyu** [comment]
Agree. 
New 1 - 0 Old smartDashBoard

**Comment by Asap7772** [comment]
Can I start working on a part of the robot?

Thanks,
Anikait Singh

**Comment by ghost** [comment]
What Anikait said.

**Comment by aravindkoneru** [comment]
You guys should have the programming priority list. Just look at what's done and write what isn't. Feel free to make pull requests and contributions.
